### ISSUE TITLE
[feat]: Keybindings helper like `?` in Lazygit

### ISSUE THREAD

**Issue by jaymorelli96** [jorgerojas26/lazysql#26]
Would be awesome to have this feature builtin. I am pretty busy this week but maybe next week I can take a look at that

**Comment by jorgerojas26** [comment]
Yeah, that is in the roadmap section of the README. But for now, i'm focusing on solving important bugs, adding support to more RDBMS and that kind of thing.

But of course this would be awesome and i'm sure i'll eventually implemented.

PRs are also welcome here.

Thank you for pointing it out :P

**Comment by KevenGoncalves** [comment]
I'm working in this feature, soon I will open a PR

**Comment by rsmirnov90** [comment]
Hi, was wondering if anyone had time to work on this? 

If not, I would love to try to tackle this feature...

@jorgerojas26 Would you be open to the idea of having the keybindings display on a bottom bar instead of a pop-up window (like they do in mc/far2l/htop/etc)? I think this would be helpful especially for non-vim users who still live in the console.

**Comment by jorgerojas26** [comment]
> Hi, was wondering if anyone had time to work on this?
> 
> If not, I would love to try to tackle this feature...
> 
> @jorgerojas26 Would you be open to the idea of having the keybindings display on a bottom bar instead of a pop-up window (like they do in mc/far2l/htop/etc)? I think this would be helpful especially for non-vim users who still live in the console.

Sorry for late response. I don't like the idea of a bottom bar because i'm the kind of person who likes more clean and concrete UI interfaces, easy to understand, not with a lot of information to digest at once. I think many people knows that a '?' keybinding is for showing help in some way, so, a popup is more versatile because you can put a maybe a search input, a clear and concise description, etc. But anyways, i have used programs (like [zellij](https://zellij.dev)) that implements this as a bottom bar successfully, so i'm open to it.
